---
kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

event:
  - push

steps:
  - name: restore_cache
    image: meltwater/drone-cache
    pull: true
    settings:
      restore: true
      debug: true
      cache_key: '{{ .Commit.Branch }}'
      access_key:
        from_secret: aws-key-id
      secret_key:
        from_secret: aws-secret-key
      bucket:
        from_secret: aws-cache-bucket
      region:
        from_secret: aws-region
      local_root: /drone/src
      mount:
        - .m2
        - src/test/resources/big
        - blast

  - name: deploy
    image: maven:3-adoptopenjdk-8
    commands:
      - mkdir -p $${HOME}/.m2
      - echo '<settings><servers><server><id>therepo</id><username>$${repo.user}</username><password>$${repo.pass}</password></server></servers></settings>' > $${HOME}/.m2/settings.xml
      - mvn deploy -DskipTests -DaltDeploymentRepository=therepo::default::$${DEPLOY_REPO} -Drepo.user=$${DEPLOY_USER} -Drepo.pass=$${DEPLOY_PASS} -Drevision=${DRONE_COMMIT_SHA:0:7}
      - ls -la
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"
      AWS_REGION:
        from_secret: aws-region
      DEPLOY_REPO:
        from_secret: maven-deploy-repo
      DEPLOY_USER:
        from_secret: aws-key-id
      DEPLOY_PASS:
        from_secret: aws-secret-key
    when:
      event:
        exclude:
          - pull_request

  - name: build_and_test
    image: maven:3-adoptopenjdk-8
    commands:
      - ./init.sh
      - mvn clean test
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"

  - name: rebuild_cache
    image: meltwater/drone-cache
    settings:
      rebuild: true
      debug: true
      cache_key: '{{ .Commit.Branch }}'
      access_key:
        from_secret: aws-key-id
      secret_key:
        from_secret: aws-secret-key
      bucket:
        from_secret: aws-cache-bucket
      region:
        from_secret: aws-region
      local_root: /drone/src
      mount:
        - .m2
        - src/test/resources/big
        - blast

---
kind: signature
hmac: d02746c6286deb3080bbebb9d8240797c418e8e8228df21b6bed55938a50ed26

...
