---
kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

event:
  - push

steps:
  - name: restore_cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp-cache-host
      port:
        from_secret: sftp-cache-port
      username:
        from_secret: sftp-cache-user
      password:
        from_secret: sftp-cache-password
      path: /home
      restore: true
      mount:
        - .m2

  - name: deploy
    image: maven:3-adoptopenjdk-8
    commands:
      - mkdir -p $${HOME}/.m2
      - echo '<settings><servers><server><id>therepo</id><username>$${repo.user}</username><password>$${repo.pass}</password></server></servers></settings>' > $${HOME}/.m2/settings.xml
      - mvn deploy -DskipTests -DaltDeploymentRepository=therepo::default::$${DEPLOY_REPO} -Drepo.user=$${DEPLOY_USER} -Drepo.pass=$${DEPLOY_PASS} -Drevision=${DRONE_COMMIT_SHA:0:7}
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"
      DEPLOY_REPO:
        from_secret: maven-deploy-repo
      DEPLOY_USER:
        from_secret: maven-deploy-user
      DEPLOY_PASS:
        from_secret: maven-deploy-pass
    when:
      event:
        exclude:
          - pull_request

  - name: build_and_test
    image: maven:3-adoptopenjdk-8
    commands:
      - mvn clean test
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"

  - name: rebuild_cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp-cache-host
      port:
        from_secret: sftp-cache-port
      username:
        from_secret: sftp-cache-user
      password:
        from_secret: sftp-cache-password
      path: /home
      rebuild: true
      mount:
        - .m2

---
kind: signature
hmac: bdb3272f93844ad8d4e181824ed026889945ab8cb72ee4479e79ae6183e25a74

...
