---
kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

event:
  - push

steps:
  - name: restore_cache
    image: meltwater/drone-cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws-key-id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws-secret-key
    pull: true
    settings:
      restore: true
      bucket:
        from_secret: aws-cache-bucket
      region:
        from_secret: aws-region
      mount:
        - .m2
        - src/test/resources/big
        - blast

  - name: deploy
    image: maven:3-adoptopenjdk-8
    commands:
      - df -h
      - mkdir -p $${HOME}/.m2
      - echo '<settings><servers><server><id>therepo</id><username>$${repo.user}</username><password>$${repo.pass}</password></server></servers></settings>' > $${HOME}/.m2/settings.xml
      - mvn deploy -DskipTests -DaltDeploymentRepository=therepo::default::$${DEPLOY_REPO} -Drepo.user=$${DEPLOY_USER} -Drepo.pass=$${DEPLOY_PASS} -Drevision=${DRONE_COMMIT_SHA:0:7}
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"
      DEPLOY_REPO:
        from_secret: maven-deploy-repo
      DEPLOY_USER:
        from_secret: maven-deploy-user
      DEPLOY_PASS:
        from_secret: maven-deploy-pass
    when:
      event:
        exclude:
          - pull_request

#  - name: build_and_test
#    image: maven:3-adoptopenjdk-8
#    commands:
#      - ./init.sh
#      - mvn clean test
#    environment:
#      MAVEN_OPTS: "-Dmaven.repo.local=/drone/src/.m2"

  - name: rebuild_cache
    image: meltwater/drone-cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws-key-id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws-secret-key
    settings:
      rebuild: true
      bucket:
        from_secret: aws-cache-bucket
      region:
        from_secret: aws-region
      mount:
        - .m2
        - src/test/resources/big
        - blast

---
kind: signature
hmac: 6a7bb32b764f0e8a8f096d6219ddc83f35af3eb0ed237af4c3f7d26acb5f5838

...
